const workouts = {
    "Prvi-Trening": [],
    "Drugi-Trening": [],
    "Bolesna-Nevena": [
        ["Prepare to start", 10],
        ["Free warm up", 12], //180
        ["Standing waist twist", 30],
        ["Standing waist twist to halos", 30],
        ["Rest", 10],
        ["Discobolus swing to uppercut left", 30],
        ["Discobolus swing uppercut right", 30],
        ["Rest", 10],
        ["Squat thruster to reverse lunge press left", 40],
        ["Squat thruster to reverse lunge press right", 40],
        ["Rest", 10],
        ["Side swings both hands", 30],
        ["Rest", 10],
        ["Standing windmill left", 40],
        ["Standing windmill right", 40],
        ["Rest", 20],
        ["Lunge with waist twist left", 40],
        ["Lunge with waist twist right", 40],
        ["Rest", 20],
        ["Toe squat", 40],
        ["Rest", 10],
        ["Kickstand squat left", 30],
        ["Kickstand squat right", 30],
        ["Rest", 20],
        ["Single RDL w/ row, knee lift, press left", 60],
        ["Single RDL w/ row, knee lift, press right", 60],
        ["Rest", 20],
        ["Kneeling quad extension to bicep/tricep curl", 60],
        ["Rest", 20],
        ["Sumo squat pulses to lunge pulses", 60],
        ["Rest", 20],
        ["Snatch left", 30],
        ["Snatch right", 30],
        ["Rest", 20],
        ["Half shin box get up left", 30],
        ["Half shin box get up right", 30],
        ["Rest", 10],
        ["Glute bridge with press left", 30],
        ["Glute bridge with press right", 30],
        ["Rest", 10],
        ["Dead bug", 60],
        ["Reverse plank knee tucks", 40],
        ["Rest", 10],
        ["Plank reach elbow to T", 50],
        ["Rest", 10],
        ["Push up", 60],
        ["Rest", 10],
        ["Australian rows", 60],
        ["Rest", 10],
        ["Z press", 30],
        ["Lateral raises", 30],
        ["High plank to low plank", 30],
        ["Rest", 10],
        ["Neck flexion", 90],
    ],
};
