const workouts = {
    "Ghibli-Gains": [
        ["Prepare to start", 10],
        ["Free warm up", 180],
        ["Standing waist twist", 30],
        ["Standing waist twist to halos, bicep curl, tricep curl", 30],
        ["Rest", 10],
        ["Discobolus swing to uppercut left", 30],
        ["Discobolus swing uppercut right", 30],
        ["Rest", 10],
        ["Squat thruster to reverse lunge press left", 40],
        ["Squat thruster to reverse lunge press right", 40],
        ["Rest", 10],
        ["Side swings both hands", 30],
        ["Rest", 10],
        ["Single swing to high pull left", 30],
        ["Single swing to high pull right", 30],
        ["Rest", 10],
        ["Lunge with waist twist left", 40],
        ["Lunge with waist twist right", 40],
        ["Rest", 20],
        ["Lunge windmill left", 40],
        ["Lunge windmill right", 40],
        ["Rest", 20],
        ["Toe squat", 40],
        ["Rest", 10],
        ["Kickstand squat left", 30],
        ["Kickstand squat right", 30],
        ["Rest", 20],
        ["Single RDL with row, knee lift, press left", 60],
        ["Single RDL with row, knee lift, press right", 60],
        ["Rest", 20],
        ["Sumo squat pulses to side coil lunge pulses", 60],
        ["Rest", 20],
        ["Squat to bicep curl to press to tricep curl", 60],
        ["Rest", 20],
        ["Half shin box get up left", 40],
        ["Half shin box get up right", 40],
        ["Rest", 20],
        ["90 90 box get up left", 40],
        ["90 90 box get up right", 40],
        ["Rest", 10],
        ["Glute bridge with press left", 30],
        ["Glute bridge with press right", 30],
        ["Rest", 10],
        ["Dead bug", 60],
        ["Reverse plank knee tucks", 40],
        ["Rest", 10],
        ["Plank reach elbow to T", 50],
        ["Rest", 10],
        ["Push up", 60],
        ["Rest", 10],
        ["Australian rows", 60],
        ["Rest", 10],
        ["Z press", 30],
        ["Lateral raises", 30],
        ["High plank hold", 30],
        ["Rest", 10],
        ["Neck flexion", 60],
    ],
};
