const workouts = {
    "Ghibli-Gains": [
        ["Prepare to start", 10],
        ["Free warm up", 180],
        ["Standing waist twist", 30],
        ["Standing waist twist to halos, bicep curl, tricep curl", 30],
        ["Rest", 10],
        ["Discobolus swing to uppercut left", 30],
        ["Discobolus swing uppercut right", 30],
        ["Rest", 10],
        ["Squat thruster to reverse lunge press left", 40],
        ["Squat thruster to reverse lunge press right", 40],
        ["Rest", 10],
        ["Side swings both hands", 30],
        ["Rest", 10],
        ["Single swing to high pull left", 30],
        ["Single swing to high pull right", 30],
        ["Rest", 10],
        ["Lunge with waist twist left", 40],
        ["Lunge with waist twist right", 40],
        ["Rest", 20],
        ["Lunge windmill left", 40],
        ["Lunge windmill right", 40],
        ["Rest", 20],
        ["Toe squat", 40],
        ["Rest", 10],
        ["Kickstand squat left", 30],
        ["Kickstand squat right", 30],
        ["Rest", 20],
        ["Single RDL with row, knee lift, press left", 60],
        ["Single RDL with row, knee lift, press right", 60],
        ["Rest", 20],
        ["Sumo squat pulses to side coil lunge pulses", 60],
        ["Rest", 20],
        ["Squat to bicep curl to press to tricep curl", 60],
        ["Rest", 20],
        ["Half shin box get up rotation left", 40],
        ["Half shin box get up rotation right", 40],
        ["Rest", 20],
        ["90 90 box get up rotation left", 40],
        ["90 90 box get up rotation right", 40],
        ["Rest", 10],
        ["Glute bridge with press left", 30],
        ["Glute bridge with press right", 30],
        ["Rest", 10],
        ["Dead bug", 60],
        ["Reverse plank knee tucks", 40],
        ["Rest", 10],
        ["Plank reach elbow to T", 50],
        ["Rest", 10],
        ["Knee Push up", 60],
        ["Rest", 10],
        ["Australian rows", 60],
        ["Rest", 10],
        ["Z press", 30],
        ["Lateral raises", 30],
        ["High plank hold", 30],
        ["Rest", 10],
        ["Neck flexion", 60],
    ],
    "Forest-Form": [
        ["Prepare to start", 10],
        ["Free warm up", 180],
        ["Standing bicycle", 30],
        ["High plank cross tucks", 30],
        ["Rest", 10],
        ["Squat to standing bicycle", 60],
        ["Rest", 10],
        ["Squat to reverse lunge left", 40],
        ["Squat to reverse lunge right", 40],
        ["Rest", 10],
        ["Side swings both hands", 30],
        ["Rest", 10],
        ["Side lunge with waist twist left", 30],
        ["Side lunge with waist twist right", 30],
        ["Rest", 10],
        ["Lunge with waist twist left", 40],
        ["Lunge with waist twist right", 40],
        ["Rest", 20],
        ["Lunge with spinal twist left", 40],
        ["Lunge with spinal twist right", 40],
        ["Rest", 20],
        ["Toe squat", 40],
        ["Rest", 10],
        ["Kickstand squat left", 30],
        ["Kickstand squat right", 30],
        ["Rest", 20],
        ["Single RDL with row to knee lift", 60],
        ["Single RDL with row to knee lift", 60],
        ["Rest", 20],
        ["Sumo squat pulses to side coil lunge pulses", 60],
        ["Rest", 20],
        ["Squat to crab tricept extension", 60],
        ["Rest", 20],
        ["Half shin box get up rotation left", 40],
        ["Half shin box get up rotation right", 40],
        ["Rest", 20],
        ["90 90 box get up rotation left", 40],
        ["90 90 box get up rotation right", 40],
        ["Rest", 10],
        ["Glute bridge left", 30],
        ["Glute bridge right", 30],
        ["Rest", 10],
        ["Dead bug", 60],
        ["Reverse plank knee tucks", 40],
        ["Rest", 10],
        ["Plank reach elbow to T", 50],
        ["Rest", 10],
        ["Knee Push up", 60],
        ["Rest", 10],
        ["Supermans", 60],
        ["Rest", 10],
        ["Z press", 30],
        ["Lateral raises", 30],
        ["High plank hold", 30],
        ["Rest", 10],
        ["Neck flexion", 60],
    ],
    "Endure-I-Guess": [
        ["Mountain Climbers", 40],
        ["Rest", 20],
        ["Burpees", 40],
        ["Rest", 20],
        ["Squat Jumpers", 40],
        ["Rest", 20],
        ["Lunge Jumpers", 40],
        ["Rest", 20],
        ["High Knees", 40],
        ["Rest", 20],
        ["Rest", 60],
    ],
    "15-min-Full-Body-Blast": [
        ["Prepare to start", 10],
        ["Free warm up", 180],
        ["Standing waist twist with halo", 30],
        ["Double swing", 60],
        ["Rest", 10],
        ["Single swing left", 30],
        ["Single swing right", 30],
        ["Rest", 10],
        ["Squat thruster to reverse lunge press left", 40],
        ["Squat thruster to reverse lunge press right", 40],
        ["Rest", 10],
        ["Side swings both hands", 30],
        ["Rest", 10],
        ["Toe squat with press", 60],
        ["Rest", 10],
        ["Sumo squat pulses to side coil lunge pulses", 60],
        ["Rest", 20],
        ["Overhead press to windmill left", 40],
        ["Overhead press to windmill right", 40],
        ["Push ups (standard or knee)", 40],
        ["Australian rows", 40],
        ["Rest", 10],
        ["Glute bridge with press left", 30],
        ["Glute bridge with press right", 30],
        ["Rest", 10],
        ["Dead bug", 60],
        ["Neck flexion", 60],
    ],
};
